"""empty message

Revision ID: a8c7c6db636e
Revises: e8c41908dd00
Create Date: 2025-12-09 09:35:16.055022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c7c6db636e'
down_revision: Union[str, Sequence[str], None] = 'e8c41908dd00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('id_telegram', sa.Integer(), nullable=True))
    op.drop_column('wallets', 'id_wallet_telegram')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('id_wallet_telegram', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('wallets', 'id_telegram')
    # ### end Alembic commands ###
